import { PathMetadata } from "@/app/utils/path";
import { BRAND_COLOURS } from "@blueshift-gg/ui-components";

export const paths: PathMetadata[] = [
  {
    slug: "solana-developer-foundations",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    estimatedHours: 8,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "tokens-on-solana" },
      { type: "course", slug: "nfts-on-solana" },
    ],
  },
  {
    slug: "anchor-mastery",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 2,
    isFeatured: true,
    estimatedHours: 20,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "anchor-for-dummies" },
      { type: "challenge", slug: "anchor-vault" },
      { type: "course", slug: "spl-token-with-anchor" },
      { type: "challenge", slug: "anchor-escrow" },
      { type: "course", slug: "token-2022-with-anchor" },
      { type: "challenge", slug: "anchor-flash-loan" },
    ],
  },
  {
    slug: "native-rust-developer",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 3,
    isFeatured: true,
    estimatedHours: 30,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "pinocchio-for-dummies" },
      { type: "challenge", slug: "pinocchio-vault" },
      { type: "course", slug: "token-2022-program" },
      { type: "challenge", slug: "pinocchio-escrow" },
      { type: "course", slug: "testing-with-mollusk" },
      { type: "challenge", slug: "pinocchio-amm" },
    ],
  },
  {
    slug: "typescript-client-developer",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    estimatedHours: 15,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "tokens-on-solana" },
      { type: "course", slug: "spl-token-with-web3js" },
      { type: "course", slug: "token-2022-with-web3js" },
      { type: "course", slug: "testing-with-litesvm" },
    ],
  },
  {
    slug: "security-specialist",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 2,
    isFeatured: true,
    estimatedHours: 12,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "program-security" },
      { type: "course", slug: "secp256r1-on-solana" },
      { type: "course", slug: "winternitz-signatures-on-solana" },
    ],
  },
  {
    slug: "testing-and-tooling",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 2,
    isFeatured: false,
    estimatedHours: 10,
    steps: [
      { type: "course", slug: "testing-with-mollusk" },
      { type: "course", slug: "testing-with-litesvm" },
      { type: "course", slug: "testing-with-surfpool" },
      { type: "course", slug: "create-your-sdk-with-codama" },
    ],
  },
  {
    slug: "advanced-low-level",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 4,
    isFeatured: false,
    estimatedHours: 25,
    steps: [
      { type: "course", slug: "pinocchio-for-dummies" },
      { type: "course", slug: "introduction-to-assembly" },
      { type: "course", slug: "instruction-introspection" },
      { type: "challenge", slug: "pinocchio-vault" },
      { type: "challenge", slug: "pinocchio-escrow" },
      { type: "challenge", slug: "pinocchio-amm" },
    ],
  },
  {
    slug: "token-developer",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 2,
    isFeatured: false,
    estimatedHours: 18,
    steps: [
      { type: "course", slug: "tokens-on-solana" },
      { type: "course", slug: "spl-token-with-web3js" },
      { type: "course", slug: "spl-token-with-anchor" },
      { type: "course", slug: "token-2022-program" },
      { type: "course", slug: "token-2022-with-web3js" },
      { type: "course", slug: "token-2022-with-anchor" },
    ],
  },
  {
    slug: "payments-and-commerce",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: false,
    estimatedHours: 6,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "tokens-on-solana" },
      { type: "course", slug: "solana-pay" },
    ],
  },
  {
    slug: "solana-mobile-mastery",
    language: "Mobile",
    color: BRAND_COLOURS.mobile,
    difficulty: 2,
    isFeatured: true,
    estimatedHours: 18,
    steps: [
      { type: "course", slug: "mobile-dapp-fundamentals" },
      { type: "course", slug: "mwa-deep-dive" },
      { type: "course", slug: "embedded-wallets" },
      { type: "course", slug: "solana-mobile-client" },
      { type: "course", slug: "dapp-store-publishing" },
    ],
  },
];
