import { ChallengeMetadata } from "@/app/utils/challenges";
import { BRAND_COLOURS } from "@blueshift-gg/ui-components";

export const challenges: ChallengeMetadata[] = [
  {
    slug: "anchor-vault",
    language: "Anchor",
    color: BRAND_COLOURS.anchor,
    difficulty: 1,
    isFeatured: true,
    unitName: "Anchor Vault",
    apiPath: "/v1/verify/anchor/vault",
    tags: ["Anchor", "Vault", "DeFi"],
    requirements: [
      { instructionKey: "deposit" },
      { instructionKey: "withdraw" },
    ],
    collectionMintAddress: "53tiK9zY67DuyA1tgQ6rfNgixMB1LiCP9D67RgfbCrpz",
  },
  {
    slug: "anchor-escrow",
    language: "Anchor",
    color: BRAND_COLOURS.anchor,
    difficulty: 1,
    isFeatured: true,
    unitName: "Anchor Escrow",
    apiPath: "/v1/verify/anchor/escrow",
    tags: ["Anchor", "Escrow", "DeFi"],
    pages: [{ slug: "make" }, { slug: "take" }, { slug: "refund" }],
    requirements: [
      { instructionKey: "make" },
      { instructionKey: "take" },
      { instructionKey: "refund" },
    ],
    collectionMintAddress: "2E5K7FxDWGXkbRpFEAkhR8yQwiUBGggVyng2vaAhah5L",
  },
  {
    slug: "anchor-flash-loan",
    language: "Anchor",
    color: BRAND_COLOURS.anchor,
    difficulty: 2,
    isFeatured: true,
    unitName: "Anchor Flash Loan",
    apiPath: "/v1/verify/anchor/flash-loan",
    pages: [{ slug: "borrow" }, { slug: "repay" }],
    requirements: [
      { instructionKey: "flash_loan" },
    ],
    collectionMintAddress: "4HJoxVtwKsLNKx3QsxG34FW39ENQZSZHmXi7wsuEVrAy",
  },
  {
    slug: "pinocchio-vault",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 2,
    isFeatured: true,
    unitName: "Pinocchio Vault",
    apiPath: "/v1/verify/pinocchio/vault",
    requirements: [
      { instructionKey: "deposit" },
      { instructionKey: "withdraw" },
    ],
    collectionMintAddress: "AL38QM96SDu4Jpx7UGcTcaLtwvWPVgRUzg9PqC787djK",
  },
  {
    slug: "pinocchio-escrow",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 2,
    isFeatured: true,
    unitName: "Pinocchio Escrow",
    apiPath: "/v1/verify/pinocchio/escrow",
    pages: [
      { slug: "make" },
      { slug: "take" },
      { slug: "refund" },
      { slug: "conclusion" },
    ],
    requirements: [
      { instructionKey: "make" },
      { instructionKey: "take" },
      { instructionKey: "refund" },
    ],
    collectionMintAddress: "HTXVJ8DD6eSxkVyDwgddxGw8cC8j6kXda3BUipA43Wvs",
  },
  {
    slug: "pinocchio-amm",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 3,
    isFeatured: true,
    unitName: "Pinocchio AMM",
    apiPath: "/v1/verify/pinocchio/amm",
    tags: ["Rust", "AMM", "DeFi", "Swap"],
    pages: [
      { slug: "initialize" },
      { slug: "deposit" },
      { slug: "withdraw" },
      { slug: "swap" },
      { slug: "conclusion" },
    ],
    requirements: [
      { instructionKey: "initialize" },
      { instructionKey: "deposit" },
      { instructionKey: "withdraw" },
      { instructionKey: "swap" },
    ],
    collectionMintAddress: "9Lz67dYmMG8JzkkvfWQuVgGR12JdjV54p9e8TViKiqQz",
  },
  {
    slug: "pinocchio-secp256r1-vault",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 2,
    isFeatured: true,
    unitName: "Pinocchio Secp256r1 Vault",
    apiPath: "/v1/verify/pinocchio/secp256r1-vault",
    requirements: [
      { instructionKey: "deposit" },
      { instructionKey: "withdraw" },
    ],
    collectionMintAddress: "4NKZ2B5zeG9TGZifzfnG7Zw28P3ZetjaS6xPVKW5MHrp",
  },
  {
    slug: "pinocchio-flash-loan",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 2,
    isFeatured: true,
    unitName: "Pinocchio Flash Loan",
    apiPath: "/v1/verify/pinocchio/flash-loan",
    pages: [{ slug: "borrow" }, { slug: "repay" }],
    requirements: [
      { instructionKey: "flash_loan" },
    ],
    collectionMintAddress: "9L975Y5Y6Gub2RHNFECyP3cJh3aiE1eVgo2A6mVV8YQu",
  },
  {
    slug: "typescript-mint-an-spl-token",
    language: "Typescript",
    color: BRAND_COLOURS.typescript,
    difficulty: 1,
    isFeatured: true,
    unitName: "Mint an SPL Token",
    apiPath: "/v1/verify/typescript/mint-an-spl-token",
    tags: ["TypeScript", "SPL", "Token"],
    requirements: [
      { instructionKey: "create_mint_account" },
      { instructionKey: "initialize_mint" },
      { instructionKey: "create_token_account" },
      { instructionKey: "mint_to" },
    ],
    collectionMintAddress: "2NVDhSXZck9AX2aUdPSxMemLN2wtqEd5sNEcwuZVCbHW",
  },
  {
    slug: "assembly-memo",
    language: "Assembly",
    color: BRAND_COLOURS.assembly,
    difficulty: 2,
    isFeatured: true,
    unitName: "Assembly Memo",
    apiPath: "/v1/verify/assembly/memo",
    requirements: [
      { instructionKey: "log" },
      { instructionKey: "log_different" },
    ],
    collectionMintAddress: "J4TtfoyvksdNjLAqs1yXbZwe8wjVCX6TSjYyGMhU6BU7",
  },
  {
    slug: "assembly-slippage",
    language: "Assembly",
    color: BRAND_COLOURS.assembly,
    difficulty: 3,
    isFeatured: true,
    unitName: "Assembly Slippage",
    apiPath: "/v1/verify/assembly/slippage",
    requirements: [
      { instructionKey: "slippage" },
      { instructionKey: "slippage_failure" },
      { instructionKey: "slippage_token2022" },

    ],
    collectionMintAddress: "EEzodaKLa7KKbWdUAtjTJxjQXgrfQkkDEnQWzGTYFBBf",
  },
  {
    slug: "assembly-timeout",
    language: "Assembly",
    color: BRAND_COLOURS.assembly,
    difficulty: 2,
    isFeatured: true,
    unitName: "Assembly Timeout",
    apiPath: "/v1/verify/assembly/timeout",
    requirements: [
      { instructionKey: "timeout" },
      { instructionKey: "timeout_failure" },
    ],
    collectionMintAddress: "FW9LJEjJwGL1fkAjfM9HxuJuftTU9KrRvPBgP5ZzJx3D",
  },
  {
    slug: "pinocchio-quantum-vault",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 2,
    isFeatured: true,
    unitName: "Pinocchio Quantum Vault",
    apiPath: "/v1/verify/pinocchio/quantum-vault",
    pages: [
      { slug: "open" },
      { slug: "split" },
      { slug: "close" },
    ],
    requirements: [
      { instructionKey: "open" },
      { instructionKey: "close" },
    ],
    collectionMintAddress: "HEZn1PnhPBejGJQS7wtNAeBv73ExhqDhxYMxdRs8AM8W",
  },
];
