import { CourseMetadata, withCourseNumber } from "@/app/utils/course";
import { BRAND_COLOURS } from "@blueshift-gg/ui-components";

export const courses: CourseMetadata[] = withCourseNumber([
  {
    slug: "introduction-to-blockchain-and-solana",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "blockchain-fundamentals" },
      { slug: "blockchain-evolution" },
      { slug: "introduction-to-solana" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "anchor-for-dummies",
    language: "Anchor",
    color: BRAND_COLOURS.anchor,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "anchor-101" },
      { slug: "anchor-accounts" },
      { slug: "anchor-instructions" },
      { slug: "testing-your-program" },
      { slug: "program-deployment" },
      { slug: "client-side-development" },
      { slug: "advanced-anchor" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "pinocchio-for-dummies",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "pinocchio-101" },
      { slug: "pinocchio-accounts" },
      { slug: "pinocchio-instructions" },
      { slug: "pinocchio-errors" },
      { slug: "reading-and-writing-data" },
      { slug: "testing-your-program" },
      { slug: "performance" },
      { slug: "middleware-entrypoint" },
      { slug: "batch-instructions" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "introduction-to-assembly",
    language: "Assembly",
    color: BRAND_COLOURS.assembly,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "assembly-101" },
      { slug: "registers-and-memory" },
      { slug: "instructions" },
      { slug: "tooling" },
      { slug: "program-example" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "program-security",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "signer-checks" },
      { slug: "owner-checks" },
      { slug: "data-matching" },
      { slug: "duplicate-mutable-accounts" },
      { slug: "reinitialization-attacks" },
      { slug: "revival-attacks" },
      { slug: "arbitrary-cpi" },
      { slug: "type-cosplay" },
      { slug: "pda-sharing" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "secp256r1-on-solana",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "secp256r1-with-anchor" },
      { slug: "secp256r1-with-pinocchio" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "tokens-on-solana",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "mint-and-token-accounts" },
      { slug: "functionalities" },
      { slug: "metaplex-token-metadata" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "nfts-on-solana",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "metaplex-token-metadata" },
      { slug: "metaplex-core" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "spl-token-with-web3js",
    language: "Typescript",
    color: BRAND_COLOURS.typescript,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "mint-to" },
      { slug: "transfer" },
      { slug: "burn" },
      { slug: "close-account" },
      { slug: "approve-and-revoke" },
      { slug: "freeze-and-thaw" },
      { slug: "set-authority" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "spl-token-with-anchor",
    language: "Anchor",
    color: BRAND_COLOURS.anchor,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "mint-to" },
      { slug: "transfer" },
      { slug: "burn" },
      { slug: "close-account" },
      { slug: "approve-and-revoke" },
      { slug: "freeze-and-thaw" },
      { slug: "set-authority" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "token-2022-program",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "token-extensions" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "token-2022-with-web3js",
    language: "Typescript",
    color: BRAND_COLOURS.typescript,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "transfer-fee-extension" },
      { slug: "mint-close-authority-extension" },
      { slug: "default-account-state-extension" },
      { slug: "immutable-owner-extension" },
      { slug: "memo-transfer-extension" },
      { slug: "non-transferable-extension" },
      { slug: "interest-bearing-extension" },
      { slug: "cpi-guard-extension" },
      { slug: "permanent-delegate-extension" },
      { slug: "metadata-extension" },
      { slug: "group-and-member-extension" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "token-2022-with-anchor",
    language: "Anchor",
    color: BRAND_COLOURS.anchor,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "transfer-fee-extension" },
      { slug: "mint-close-authority-extension" },
      { slug: "default-account-state-extension" },
      { slug: "immutable-owner-extension" },
      { slug: "memo-transfer-extension" },
      { slug: "non-transferable-extension" },
      { slug: "interest-bearing-extension" },
      { slug: "cpi-guard-extension" },
      { slug: "permanent-delegate-extension" },
      { slug: "metadata-extension" },
      { slug: "group-and-member-extension" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "instruction-introspection",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "introspection-with-anchor" },
      { slug: "introspection-with-pinocchio" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "testing-with-mollusk",
    language: "Rust",
    color: BRAND_COLOURS.rust,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "mollusk-101" },
      { slug: "advanced-functionalities" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "solana-pay",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "transfer-request" },
      { slug: "transaction-request" },
      { slug: "conclusion" },
     ],
  },
  {
    slug: "create-your-sdk-with-codama",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "codama-from-scratch" },
      { slug: "codama-with-anchor" },
      { slug: "updating-codama-idl" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "winternitz-signatures-on-solana",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "introduction" },
      { slug: "winternitz-signatures-with-anchor" },
      { slug: "winternitz-signatures-with-pinocchio" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "testing-with-litesvm",
    language: "Typescript",
    color: BRAND_COLOURS.typescript,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "litesvm-101" },
      { slug: "typescript" },
      { slug: "rust" },
      { slug: "conclusion" },
    ],
  },
  {
    slug: "testing-with-surfpool",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    lessons: [
      { slug: "surfpool-101" },
      { slug: "advanced-functionalities" },
      { slug: "conclusion" },
    ],
  },
]);
